@startuml editExistingEvent
title Edit Existing Event
actor Admin
Admin -> System: editEvent(eventId, date, location, category)
System -> Server: handleEvents(HttpExchange exchange)
Server -> Database: updateEvent (event)
Database --> Server: success
Server --> System: success
System --> Admin: event updated
@enduml