@startuml searchEvents
title Search Events
actor User
User -> System: searchEvents(date, location, category)
System -> Server: handleEvents(HttpExchange exchange)
Server -> Database: Database.getSearchedEvents(filters)
Database --> Server: response.toString()
Server --> System: sendResponse(exchange, 200, json);
System --> User: Display events list
@enduml